import {Item, Slot} from "./Item";
import {items} from "./Items";

export const gearSets: Item[][] = [];

let gearSet: Item[] = [];
let item = items.get("Osmumten's fang") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Osmumten's fang") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Neitiznot faceguard") as Item;
gearSet.push(item);
item = items.get("Bandos chestplate") as Item;
gearSet.push(item);
item = items.get("Bandos tassets") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of fury") as Item;
gearSet.push(item);
item = items.get("Fire cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Ghrazi rapier") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Zamorakian hasta") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Zamorakian hasta") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Neitiznot faceguard") as Item;
gearSet.push(item);
item = items.get("Bandos chestplate") as Item;
gearSet.push(item);
item = items.get("Bandos tassets") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of fury") as Item;
gearSet.push(item);
item = items.get("Fire cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Scythe of vitur") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Scythe of vitur") as Item;
gearSet.push(item);
item = items.get("Neitiznot faceguard") as Item;
gearSet.push(item);
item = items.get("Bandos chestplate") as Item;
gearSet.push(item);
item = items.get("Bandos tassets") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of fury") as Item;
gearSet.push(item);
item = items.get("Fire cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Toxic blowpipe") as Item;
gearSet.push(item);
item = items.get("Dragon dart") as Item;
gearSet.push(item);
item = items.get("Masori mask (f)") as Item;
gearSet.push(item);
item = items.get("Masori body (f)") as Item;
gearSet.push(item);
item = items.get("Masori chaps (f)") as Item;
gearSet.push(item);
item = items.get("Zaryte vambraces") as Item;
gearSet.push(item);
item = items.get("Necklace of anguish") as Item;
gearSet.push(item);
item = items.get("Ava's assembler") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Toxic blowpipe") as Item;
gearSet.push(item);
item = items.get("Dragon dart") as Item;
gearSet.push(item);
item = items.get("Armadyl helmet") as Item;
gearSet.push(item);
item = items.get("Armadyl chestplate") as Item;
gearSet.push(item);
item = items.get("Armadyl chainskirt") as Item;
gearSet.push(item);
item = items.get("Zaryte vambraces") as Item;
gearSet.push(item);
item = items.get("Necklace of anguish") as Item;
gearSet.push(item);
item = items.get("Ava's assembler") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Twisted bow") as Item;
gearSet.push(item);
item = items.get("Dragon arrow") as Item;
gearSet.push(item);
item = items.get("Masori mask (f)") as Item;
gearSet.push(item);
item = items.get("Masori body (f)") as Item;
gearSet.push(item);
item = items.get("Masori chaps (f)") as Item;
gearSet.push(item);
item = items.get("Zaryte vambraces") as Item;
gearSet.push(item);
item = items.get("Necklace of anguish") as Item;
gearSet.push(item);
item = items.get("Ava's assembler") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Twisted bow") as Item;
gearSet.push(item);
item = items.get("Dragon arrow") as Item;
gearSet.push(item);
item = items.get("Armadyl helmet") as Item;
gearSet.push(item);
item = items.get("Armadyl chestplate") as Item;
gearSet.push(item);
item = items.get("Armadyl chainskirt") as Item;
gearSet.push(item);
item = items.get("Zaryte vambraces") as Item;
gearSet.push(item);
item = items.get("Necklace of anguish") as Item;
gearSet.push(item);
item = items.get("Ava's assembler") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Tumeken's shadow") as Item;
gearSet.push(item);
item = items.get("Elidinis' ward (f)") as Item;
gearSet.push(item);
item = items.get("Ancestral hat") as Item;
gearSet.push(item);
item = items.get("Ancestral robe top") as Item;
gearSet.push(item);
item = items.get("Ancestral robe bottom") as Item;
gearSet.push(item);
item = items.get("Tormented bracelet") as Item;
gearSet.push(item);
item = items.get("Occult necklace") as Item;
gearSet.push(item);
item = items.get("Imbued zamorak cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Tumeken's shadow") as Item;
gearSet.push(item);
item = items.get("Book of the dead") as Item;
gearSet.push(item);
item = items.get("Ancestral hat") as Item;
gearSet.push(item);
item = items.get("Ancestral robe top") as Item;
gearSet.push(item);
item = items.get("Ancestral robe bottom") as Item;
gearSet.push(item);
item = items.get("Tormented bracelet") as Item;
gearSet.push(item);
item = items.get("Occult necklace") as Item;
gearSet.push(item);
item = items.get("Imbued zamorak cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Sanguinesti staff") as Item;
gearSet.push(item);
item = items.get("Elidinis' ward (f)") as Item;
gearSet.push(item);
item = items.get("Ancestral hat") as Item;
gearSet.push(item);
item = items.get("Ancestral robe top") as Item;
gearSet.push(item);
item = items.get("Ancestral robe bottom") as Item;
gearSet.push(item);
item = items.get("Tormented bracelet") as Item;
gearSet.push(item);
item = items.get("Occult necklace") as Item;
gearSet.push(item);
item = items.get("Imbued zamorak cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Sanguinesti staff") as Item;
gearSet.push(item);
item = items.get("Book of the dead") as Item;
gearSet.push(item);
item = items.get("Ahrim's robetop") as Item;
gearSet.push(item);
item = items.get("Ahrim's robeskirt") as Item;
gearSet.push(item);
item = items.get("Tormented bracelet") as Item;
gearSet.push(item);
item = items.get("Occult necklace") as Item;
gearSet.push(item);
item = items.get("Imbued zamorak cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Sanguinesti staff") as Item;
gearSet.push(item);
item = items.get("Elidinis' ward (f)") as Item;
gearSet.push(item);
item = items.get("Ahrim's robetop") as Item;
gearSet.push(item);
item = items.get("Ahrim's robeskirt") as Item;
gearSet.push(item);
item = items.get("Tormented bracelet") as Item;
gearSet.push(item);
item = items.get("Occult necklace") as Item;
gearSet.push(item);
item = items.get("Imbued zamorak cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Keris partisan") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Keris partisan") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Neitiznot faceguard") as Item;
gearSet.push(item);
item = items.get("Bandos chestplate") as Item;
gearSet.push(item);
item = items.get("Bandos tassets") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Fire cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Keris partisan of breaching") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Keris partisan of breaching") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Neitiznot faceguard") as Item;
gearSet.push(item);
item = items.get("Bandos chestplate") as Item;
gearSet.push(item);
item = items.get("Bandos tassets") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Fire cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);