import {Item, Slot} from "./Item";
import {items} from "./Items";

export const gearSets: Item[][] = [];

let gearSet: Item[] = [];
let item = items.get("Osmumten's fang") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Osmumten's fang") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Neitiznot faceguard") as Item;
gearSet.push(item);
item = items.get("Bandos chestplate") as Item;
gearSet.push(item);
item = items.get("Bandos tassets") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of fury") as Item;
gearSet.push(item);
item = items.get("Fire cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Ghrazi rapier") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Zamorakian hasta") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Zamorakian hasta") as Item;
gearSet.push(item);
item = items.get("Avernic defender") as Item;
gearSet.push(item);
item = items.get("Neitiznot faceguard") as Item;
gearSet.push(item);
item = items.get("Bandos chestplate") as Item;
gearSet.push(item);
item = items.get("Bandos tassets") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of fury") as Item;
gearSet.push(item);
item = items.get("Fire cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Scythe of vitur") as Item;
gearSet.push(item);
item = items.get("Torva full helm") as Item;
gearSet.push(item);
item = items.get("Torva platebody") as Item;
gearSet.push(item);
item = items.get("Torva platelegs") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of torture") as Item;
gearSet.push(item);
item = items.get("Infernal cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Scythe of vitur") as Item;
gearSet.push(item);
item = items.get("Neitiznot faceguard") as Item;
gearSet.push(item);
item = items.get("Bandos chestplate") as Item;
gearSet.push(item);
item = items.get("Bandos tassets") as Item;
gearSet.push(item);
item = items.get("Ferocious gloves") as Item;
gearSet.push(item);
item = items.get("Primordial boots") as Item;
gearSet.push(item);
item = items.get("Amulet of fury") as Item;
gearSet.push(item);
item = items.get("Fire cape") as Item;
gearSet.push(item);
gearSets.push(gearSet);

gearSet = [];
item = items.get("Toxic blowpipe") as Item;
gearSet.push(item);
item = items.get("Dragon dart") as Item;
gearSet.push(item);
item = items.get("Masori mask (f)") as Item;
gearSet.push(item);
item = items.get("Masori body (f)") as Item;
gearSet.push(item);
item = items.get("Masori chaps (f)") as Item;
gearSet.push(item);
item = items.get("Zaryte vambraces") as Item;
gearSet.push(item);
item = items.get("Necklace of anguish") as Item;
gearSet.push(item);
item = items.get("Ava's assembler") as Item;
gearSet.push(item);
gearSets.push(gearSet);