import {TargetMonster} from "./TargetMonster";
import {Raid} from "./Raid";

export const monsters = new Map<string, TargetMonster>;

let monster = new TargetMonster();
monster.name = "Ba-Ba";
monster.raid = Raid.TombsOfAmascut;
monster.imagePath = './Images/Monsters/Ba-Ba.png';
monster.defenceLevel = 80;
monster.magicLevel = 100;
monster.magicAccuracy = 0;
monster.stabDefence = 80;
monster.slashDefence = 160;
monster.crushDefence = 240;
monster.magicDefence = 280;
monster.rangedDefence = 200;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Akkha";
monster.raid = Raid.TombsOfAmascut;
monster.imagePath = './Images/Monsters/Akkha.png';
monster.defenceLevel = 80;
monster.magicLevel = 100;
monster.magicAccuracy = 115;
monster.stabDefence = 60;
monster.slashDefence = 120;
monster.crushDefence = 120;
monster.magicDefence = 10;
monster.rangedDefence = 60;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Kephri";
monster.raid = Raid.TombsOfAmascut;
monster.attribute = "Kalphite";
monster.imagePath = './Images/Monsters/Kephri.png';
monster.defenceLevel = 80;
monster.magicLevel = 125;
monster.magicAccuracy = 125;
monster.stabDefence = 60;
monster.slashDefence = 300;
monster.crushDefence = 100;
monster.magicDefence = 200;
monster.rangedDefence = 300;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Zebak";
monster.raid = Raid.TombsOfAmascut;
monster.imagePath = './Images/Monsters/Zebak.png';
monster.defenceLevel = 70;
monster.magicLevel = 100;
monster.magicAccuracy = 215;
monster.stabDefence = 160;
monster.slashDefence = 160;
monster.crushDefence = 260;
monster.magicDefence = 200;
monster.rangedDefence = 110;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Wardens P3";
monster.raid = Raid.TombsOfAmascut;
monster.imagePath = './Images/Monsters/Tumekens_Warden.png';
monster.defenceLevel = 150;
monster.magicLevel = 150;
monster.magicAccuracy = 230;
monster.stabDefence = 40;
monster.slashDefence = 40;
monster.crushDefence = 20;
monster.magicDefence = 20;
monster.rangedDefence = 20;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Kree'arra (Armadyl)";
monster.imagePath = './Images/Monsters/Kreearra.png';
monster.defenceLevel = 260;
monster.magicLevel = 200;
monster.magicAccuracy = 0;
monster.stabDefence = 180;
monster.slashDefence = 180;
monster.crushDefence = 180;
monster.magicDefence = 200;
monster.rangedDefence = 200;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "General Graardor (Bandos)";
monster.imagePath = './Images/Monsters/General_Graardor.png';
monster.defenceLevel = 250;
monster.magicLevel = 80;
monster.magicAccuracy = 0;
monster.stabDefence = 90;
monster.slashDefence = 90;
monster.crushDefence = 90;
monster.magicDefence = 298;
monster.rangedDefence = 90;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Commander Zilyana (Saradomin)";
monster.imagePath = './Images/Monsters/Commander_Zilyana.png';
monster.defenceLevel = 300;
monster.magicLevel = 300;
monster.magicAccuracy = 200;
monster.stabDefence = 100;
monster.slashDefence = 100;
monster.crushDefence = 100;
monster.magicDefence = 100;
monster.rangedDefence = 100;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "K'ril Tsutsaroth (Zamorak)";
monster.imagePath = './Images/Monsters/Kril_Tsutsaroth.png';
monster.defenceLevel = 270;
monster.magicLevel = 200;
monster.magicAccuracy = 0;
monster.stabDefence = 80;
monster.slashDefence = 80;
monster.crushDefence = 80;
monster.magicDefence = 130;
monster.rangedDefence = 80;
monsters.set(monster.name, monster);