import {TargetMonster} from "./TargetMonster";
import {Raid} from "./Raid";

export const monsters = new Map<string, TargetMonster>;

let monster = new TargetMonster();
monster.name = "Ba-Ba";
monster.raid = Raid.TombsOfAmascut;
monster.imagePath = './Images/Monsters/Ba-Ba.png';
monster.defenceLevel = 80;
//https://archive.ph/31H2d
monster.maxDefenceReduction = 20;
monster.magicLevel = 100;
monster.magicAccuracy = 0;
monster.stabDefence = 80;
monster.slashDefence = 160;
monster.crushDefence = 240;
monster.magicDefence = 280;
monster.rangedDefence = 200;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Akkha";
monster.raid = Raid.TombsOfAmascut;
monster.imagePath = './Images/Monsters/Akkha.png';
monster.defenceLevel = 80;
monster.maxDefenceReduction = 20;
monster.magicLevel = 100;
monster.magicAccuracy = 115;
monster.stabDefence = 60;
monster.slashDefence = 120;
monster.crushDefence = 120;
monster.magicDefence = 10;
monster.rangedDefence = 60;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Akkha's Shadow";
monster.raid = Raid.TombsOfAmascut;
monster.imagePath = './Images/Monsters/Akkhas_Shadow.png';
monster.defenceLevel = 30;
monster.maxDefenceReduction = 20;
monster.magicLevel = 100;
monster.magicAccuracy = 115;
monster.stabDefence = 60;
monster.slashDefence = 120;
monster.crushDefence = 120;
monster.magicDefence = 10;
monster.rangedDefence = 60;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Kephri";
monster.raid = Raid.TombsOfAmascut;
monster.isKalphite = true;
monster.imagePath = './Images/Monsters/Kephri.png';
monster.defenceLevel = 80;
monster.maxDefenceReduction = 20;
monster.magicLevel = 125;
monster.magicAccuracy = 125;
monster.stabDefence = 60;
monster.slashDefence = 300;
monster.crushDefence = 100;
monster.magicDefence = 200;
monster.rangedDefence = 300;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Zebak";
monster.raid = Raid.TombsOfAmascut;
monster.imagePath = './Images/Monsters/Zebak.png';
monster.defenceLevel = 70;
monster.maxDefenceReduction = 20;
monster.magicLevel = 100;
monster.magicAccuracy = 215;
monster.stabDefence = 160;
monster.slashDefence = 160;
monster.crushDefence = 260;
monster.magicDefence = 200;
monster.rangedDefence = 110;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Wardens P3";
monster.raid = Raid.TombsOfAmascut;
monster.imagePath = './Images/Monsters/Tumekens_Warden.png';
monster.defenceLevel = 150;
monster.maxDefenceReduction = 30;
monster.magicLevel = 150;
monster.magicAccuracy = 230;
monster.stabDefence = 40;
monster.slashDefence = 40;
monster.crushDefence = 20;
monster.magicDefence = 20;
monster.rangedDefence = 20;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Kree'arra (Armadyl)";
monster.slayerMonster = true;
monster.shortName = "Armadyl";
monster.imagePath = './Images/Monsters/Kreearra.png';
monster.defenceLevel = 260;
monster.maxDefenceReduction = 260;
monster.magicLevel = 200;
monster.magicAccuracy = 0;
monster.stabDefence = 180;
monster.slashDefence = 180;
monster.crushDefence = 180;
monster.magicDefence = 200;
monster.rangedDefence = 200;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "General Graardor (Bandos)";
monster.shortName = "Bandos";
monster.imagePath = './Images/Monsters/General_Graardor.png';
monster.defenceLevel = 250;
monster.maxDefenceReduction = 250;
monster.magicLevel = 80;
monster.magicAccuracy = 0;
monster.stabDefence = 90;
monster.slashDefence = 90;
monster.crushDefence = 90;
monster.magicDefence = 298;
monster.rangedDefence = 90;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Commander Zilyana (Saradomin)";
monster.shortName = "Saradomin";
monster.imagePath = './Images/Monsters/Commander_Zilyana.png';
monster.defenceLevel = 300;
monster.maxDefenceReduction = 300;
monster.magicLevel = 300;
monster.magicAccuracy = 200;
monster.stabDefence = 100;
monster.slashDefence = 100;
monster.crushDefence = 100;
monster.magicDefence = 100;
monster.rangedDefence = 100;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "K'ril Tsutsaroth (Zamorak)";
monster.slayerMonster = true;
monster.shortName = "Zamorak";
monster.imagePath = './Images/Monsters/Kril_Tsutsaroth.png';
monster.defenceLevel = 270;
monster.maxDefenceReduction = 270;
monster.magicLevel = 200;
monster.magicAccuracy = 0;
monster.stabDefence = 80;
monster.slashDefence = 80;
monster.crushDefence = 80;
monster.magicDefence = 130;
monster.rangedDefence = 80;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Ahrim the Blighted";
monster.shortName = "Ahrim";
monster.imagePath = './Images/Monsters/Ahrim_the_Blighted.png';
monster.defenceLevel = 100;
monster.maxDefenceReduction = 100;
monster.magicLevel = 100;
monster.magicAccuracy = 73;
monster.stabDefence = 103;
monster.slashDefence = 85;
monster.crushDefence = 117;
monster.magicDefence = 73;
monster.rangedDefence = 0;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Dharok the Wretched";
monster.shortName = "Dharok";
monster.imagePath = './Images/Monsters/Dharok_the_Wretched.png';
monster.defenceLevel = 100;
monster.maxDefenceReduction = 100;
monster.magicLevel = 1;
monster.magicAccuracy = -58;
monster.stabDefence = 252;
monster.slashDefence = 250;
monster.crushDefence = 244;
monster.magicDefence = -11;
monster.rangedDefence = 249;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Guthan the Infested";
monster.shortName = "Guthan";
monster.imagePath = './Images/Monsters/Guthan_the_Infested.png';
monster.defenceLevel = 100;
monster.maxDefenceReduction = 100;
monster.magicLevel = 1;
monster.magicAccuracy = -50;
monster.stabDefence = 259;
monster.slashDefence = 257;
monster.crushDefence = 241;
monster.magicDefence = -11;
monster.rangedDefence = 250;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Karil the Tainted";
monster.shortName = "Karil";
monster.imagePath = './Images/Monsters/Karil_the_Tainted.png';
monster.defenceLevel = 100;
monster.maxDefenceReduction = 100;
monster.magicLevel = 1;
monster.magicAccuracy = -26;
monster.stabDefence = 79;
monster.slashDefence = 71;
monster.crushDefence = 90;
monster.magicDefence = 106;
monster.rangedDefence = 100;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Torag the Corrupted";
monster.shortName = "Torag";
monster.imagePath = './Images/Monsters/Torag_the_Corrupted.png';
monster.defenceLevel = 100;
monster.maxDefenceReduction = 100;
monster.magicLevel = 1;
monster.magicAccuracy = -33;
monster.stabDefence = 221;
monster.slashDefence = 235;
monster.crushDefence = 222;
monster.magicDefence = 0;
monster.rangedDefence = 221;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Verac the Defiled";
monster.shortName = "Verac";
monster.imagePath = './Images/Monsters/Verac_the_Defiled.png';
monster.defenceLevel = 100;
monster.maxDefenceReduction = 100;
monster.magicLevel = 1;
monster.magicAccuracy = -42;
monster.stabDefence = 227;
monster.slashDefence = 230;
monster.crushDefence = 221;
monster.magicDefence = 0;
monster.rangedDefence = 225;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Corporeal Beast";
monster.shortName = "Corp";
monster.imagePath = './Images/Monsters/Corporeal_Beast.png';
monster.defenceLevel = 310;
monster.maxDefenceReduction = 310;
monster.magicLevel = 350;
monster.magicAccuracy = 0;
monster.stabDefence = 25;
monster.slashDefence = 200;
monster.crushDefence = 100;
monster.magicDefence = 150;
monster.rangedDefence = 230;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "The Maiden of Sugadinti";
monster.shortName = "Maiden";
monster.imagePath = './Images/Monsters/The_Maiden_of_Sugadinti.png';
monster.defenceLevel = 200;
monster.maxDefenceReduction = 200;
monster.magicLevel = 350;
monster.magicAccuracy = 300;
monster.stabDefence = 0;
monster.slashDefence = 0;
monster.crushDefence = 0;
monster.magicDefence = 0;
monster.rangedDefence = 0;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Pestilent Bloat";
monster.shortName = "Bloat";
monster.imagePath = './Images/Monsters/Pestilent_Bloat.png';
monster.defenceLevel = 100;
monster.maxDefenceReduction = 100;
monster.magicLevel = 150;
monster.magicAccuracy = 0;
monster.stabDefence = 40;
monster.slashDefence = 20;
monster.crushDefence = 40;
monster.magicDefence = 600;
monster.rangedDefence = 800;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Nylocas Vasilias";
monster.shortName = "Nylo";
monster.imagePath = './Images/Monsters/Nylocas_Vasilias_(melee).png';
monster.defenceLevel = 50;
monster.maxDefenceReduction = 50;
monster.magicLevel = 50;
monster.magicAccuracy = 600;
monster.stabDefence = 0;
monster.slashDefence = 0;
monster.crushDefence = 0;
monster.magicDefence = 0;
monster.rangedDefence = 0;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Sotetseg";
monster.shortName = "Sote";
monster.imagePath = './Images/Monsters/Sotetseg.png';
monster.defenceLevel = 200;
monster.maxDefenceReduction = 200;
monster.magicLevel = 250;
monster.magicAccuracy = -10;
monster.stabDefence = 70;
monster.slashDefence = 70;
monster.crushDefence = 70;
monster.magicDefence = 30;
monster.rangedDefence = 150;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Xarpus";
monster.imagePath = './Images/Monsters/Xarpus.png';
monster.defenceLevel = 250;
monster.maxDefenceReduction = 250;
monster.magicLevel = 220;
monster.magicAccuracy = 0;
monster.stabDefence = 0;
monster.slashDefence = 0;
monster.crushDefence = 0;
monster.magicDefence = 0;
monster.rangedDefence = 160;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Verzik Vitur P2";
monster.shortName = "Verzik P2";
monster.imagePath = './Images/Monsters/Verzik_Vitur_(flying).png';
monster.defenceLevel = 200;
monster.maxDefenceReduction = 200;
monster.magicLevel = 400;
monster.magicAccuracy = 80;
monster.stabDefence = 100;
monster.slashDefence = 60;
monster.crushDefence = 100;
monster.magicDefence = 70;
monster.rangedDefence = 250;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Verzik Vitur P3";
monster.shortName = "Verzik P3";
monster.imagePath = './Images/Monsters/Verzik_Vitur_(final_form).png';
monster.defenceLevel = 150;
monster.maxDefenceReduction = 150;
monster.magicLevel = 300;
monster.magicAccuracy = 80;
monster.stabDefence = 70;
monster.slashDefence = 30;
monster.crushDefence = 70;
monster.magicDefence = 100;
monster.rangedDefence = 230;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Tekton";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Tekton.png';
monster.defenceLevel = 205;
monster.maxDefenceReduction = 205;
monster.magicLevel = 205;
monster.magicAccuracy = 0;
monster.stabDefence = 155;
monster.slashDefence = 165;
monster.crushDefence = 105;
monster.magicDefence = 0;
monster.rangedDefence = 0;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Vanguard (Magic)";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Vanguard_(magic).png';
monster.defenceLevel = 160;
monster.maxDefenceReduction = 160;
monster.magicLevel = 150;
monster.magicAccuracy = 40;
monster.stabDefence = 315;
monster.slashDefence = 340;
monster.crushDefence = 400;
monster.magicDefence = 110;
monster.rangedDefence = 50;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Vanguard (Melee)";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Vanguard_(melee).png';
monster.defenceLevel = 160;
monster.maxDefenceReduction = 160;
monster.magicLevel = 150;
monster.magicAccuracy = 0;
monster.stabDefence = 150;
monster.slashDefence = 150;
monster.crushDefence = 150;
monster.magicDefence = 20;
monster.rangedDefence = 400;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Vanguard (Ranged)";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Vanguard_(ranged).png';
monster.defenceLevel = 160;
monster.maxDefenceReduction = 160;
monster.magicLevel = 150;
monster.magicAccuracy = 0;
monster.stabDefence = 55;
monster.slashDefence = 60;
monster.crushDefence = 100;
monster.magicDefence = 400;
monster.rangedDefence = 300;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Vespula";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Vespula.png';
monster.defenceLevel = 88;
monster.maxDefenceReduction = 88;
monster.magicLevel = 88;
monster.magicAccuracy = 0;
monster.stabDefence = 0;
monster.slashDefence = 0;
monster.crushDefence = 0;
monster.magicDefence = 70;
monster.rangedDefence = 60;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Vasa Nistirio";
monster.shortName = "Vasa";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Vasa_Nistirio.png';
monster.defenceLevel = 175;
monster.maxDefenceReduction = 175;
monster.magicLevel = 230;
monster.magicAccuracy = 0;
monster.stabDefence = 170;
monster.slashDefence = 190;
monster.crushDefence = 50;
monster.magicDefence = 400;
monster.rangedDefence = 60;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Muttadile (Small)";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Muttadile.png';
monster.defenceLevel = 138;
monster.maxDefenceReduction = 138;
monster.magicLevel = 1;
monster.magicAccuracy = 0;
monster.stabDefence = -5;
monster.slashDefence = 72;
monster.crushDefence = 50;
monster.magicDefence = 60;
monster.rangedDefence = 0;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Muttadile (Large)";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Muttadile.png';
monster.defenceLevel = 220;
monster.maxDefenceReduction = 220;
monster.magicLevel = 250;
monster.magicAccuracy = 0;
monster.stabDefence = -5;
monster.slashDefence = -5;
monster.crushDefence = 82;
monster.magicDefence = 60;
monster.rangedDefence = 75;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Great Olm (Head)";
monster.shortName = "Olm (Head)";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Great_Olm.png';
monster.defenceLevel = 150;
monster.maxDefenceReduction = 150;
monster.magicLevel = 250;
monster.magicAccuracy = 60;
monster.stabDefence = 200;
monster.slashDefence = 200;
monster.crushDefence = 200;
monster.magicDefence = 200;
monster.rangedDefence = 50;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Great Olm (Left Claw)";
monster.shortName = "Olm (Left Claw)";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Great_Olm.png';
monster.defenceLevel = 175;
monster.maxDefenceReduction = 175;
monster.magicLevel = 175;
monster.magicAccuracy = 60;
monster.stabDefence = 50;
monster.slashDefence = 50;
monster.crushDefence = 50;
monster.magicDefence = 200;
monster.rangedDefence = 200;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Great Olm (Right Claw)";
monster.shortName = "Olm (Right Claw)";
monster.raid = Raid.ChambersOfXeric;
monster.imagePath = './Images/Monsters/Great_Olm.png';
monster.defenceLevel = 175;
monster.maxDefenceReduction = 175;
monster.magicLevel = 87;
monster.magicAccuracy = 60;
monster.stabDefence = 200;
monster.slashDefence = 200;
monster.crushDefence = 200;
monster.magicDefence = 50;
monster.rangedDefence = 200;
monsters.set(monster.shortName, monster);


monster = new TargetMonster();
monster.name = "Undead Combat Dummy";
monster.raid = Raid.None;
monster.imagePath = './Images/Monsters/Great_Olm.png';
monster.defenceLevel = 1;
monster.maxDefenceReduction = 1;
monster.magicLevel = 1;
monster.magicAccuracy = 999;
monster.stabDefence = 0;
monster.slashDefence = 0;
monster.crushDefence = 0;
monster.magicDefence = 0;
monster.rangedDefence = 0;
monsters.set(monster.name, monster);

monster = new TargetMonster();
monster.name = "Kalphite Queen";
monster.shortName = "KQ";
monster.raid = Raid.None;
monster.slayerMonster = true;
monster.isKalphite = true;
monster.imagePath = './Images/Monsters/Kalphite_Queen.png';
monster.defenceLevel = 300;
monster.maxDefenceReduction = 300;
monster.magicLevel = 150;
monster.magicAccuracy = 0;
monster.stabDefence = 50;
monster.slashDefence = 50;
monster.crushDefence = 10;
monster.magicDefence = 100;
monster.rangedDefence = 100;
monsters.set(monster.shortName, monster);

monster = new TargetMonster();
monster.name = "Kalphite Queen (P2)";
monster.shortName = "KQ (P2)";
monster.raid = Raid.None;
monster.slayerMonster = true;
monster.isKalphite = true;
monster.imagePath = './Images/Monsters/Kalphite_Queen_2nd_form.png';
monster.defenceLevel = 300;
monster.maxDefenceReduction = 300;
monster.magicLevel = 150;
monster.magicAccuracy = 0;
monster.stabDefence = 100;
monster.slashDefence = 100;
monster.crushDefence = 100;
monster.magicDefence = 10;
monster.rangedDefence = 10;
monsters.set(monster.shortName, monster);